class Option < ActiveRecord::Base
  CITIES = ['Almeria',
            'Biliran',
            'Cabucgayan',
            'Caibiran',
            'Culaba',
            'Kawayan',
            'Maripipi',
            'Naval',
            'Borongan City',
            'Arteche',
            'Balangiga',
            'Balangkayan',
            'Can-avid',
            'Dolores',
            'General MacArthur',
            'Giporlos',
            'Guiuan',
            'Hernani',
            'Jipapad',
            'Lawaan',
            'Llorente',
            'Maslog',
            'Maydolong',
            'Mercedes',
            'Oras',
            'Quinapondan',
            'Salcedo',
            'San Julian',
            'San Policarpo',
            'Sulat',
            'Taft',
            'Tacloban',
            'Baybay',
            'Ormoc',
            'Abuyog',
            'Alangalang',
            'Albuera',
            'Babatngon',
            'Barugo',
            'Bato',
            'Burauen',
            'Calubian',
            'Capoocan',
            'Carigara',
            'Dagami',
            'Dulag',
            'Hilongos',
            'Hindang',
            'Inopacan',
            'Isabel',
            'Jaro',
            'Javier',
            'Julita',
            'Kananga',
            'La Paz',
            'Leyte',
            'MacArthur',
            'Mahaplag',
            'Matag-ob',
            'Matalom',
            'Mayorga',
            'Merida',
            'Palo',
            'Palompon',
            'Pastrana',
            'San Isidro',
            'San Miguel',
            'Santa Fe',
            'Tabango',
            'Tabontabon',
            'Tanauan',
            'Tolosa',
            'Tunga',
            'Villaba',
            'Allen',
            'Biri',
            'Bobon',
            'Capul',
            'Catarman',
            'Catubig',
            'Gamay',
            'Laoang',
            'Lapinig',
            'Las Navas',
            'Lavezares',
            'Lope de Vega',
            'Mapanas',
            'Mondragon',
            'Palapag',
            'Pambujan',
            'Rosario',
            'San Antonio',
            'San Isidro',
            'San Jose',
            'San Roque',
            'San Vicente',
            'Silvino Lobos',
            'Victoria',
            'Calbayog',
            'Catbalogan',
            'Almagro',
            'Basey',
            'Calbiga',
            'Daram',
            'Gandara',
            'Hinabangan',
            'Jiabong',
            'Marabut',
            'Matuguinao',
            'Motiong',
            'Pagsanghan',
            'Paranas',
            'Pinabacdao',
            'San Jorge',
            'San Jose de Buan',
            'San Sebastian',
            'Santa Margarita',
            'Santa Rita',
            'Santo Nino',
            'Tagapul-an',
            'Talalora',
            'Tarangnan',
            'Villareal',
            'Zumarraga',
            'Anahawan',
            'Bontoc',
            'Hinunangan',
            'Hinundayan',
            'Libagon',
            'Liloan',
            'Limasawa',
            'Maasin City',
            'Macrohon',
            'Malitbog',
            'Padre Burgos',
            'Pintuyan',
            'Saint Bernard',
            'San Francisco',
            'San Juan',
            'San Ricardo',
            'Silago',
            'Sogod',
            'Tomas Oppus'].sort
            
  PROVINCES = ['Leyte',
               'Southern Leyte',
               'Biliran',
               'Samar',
               'Eastern Samar',
               'Northern Samar'
              ].sort
  
  CONDITIONS = ['No Damage',
                'Minimal Damage',
                'Severe Damage',
                'Damage Unknown']
end